name: plantapp
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flip_card: ^0.7.0
  flutter_svg: ^2.1.0
  provider: ^6.1.5


  sqlite3_flutter_libs: ^0.5.3
  path_provider_android: ^2.2.17
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  drift_dev: ^2.15.0
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/